#!/usr/bin/env sh
# Mint a Cognito access token for this attendee's Flyte devbox.
#
# Referenced by .flyte/config.yaml as an ExternalCommand auth provider: the Flyte
# CLI runs it whenever it needs a bearer token and reads the token off stdout. That
# means it must print the token and NOTHING else — every diagnostic goes to stderr.
#
# Why this exists: the devbox authenticates via Cognito at the ALB. Humans use PKCE,
# which opens a browser. There is no browser in the Kiro sandbox, so we use the
# Cognito machine-to-machine client-credentials grant instead.
#
# Config comes from .flyte/workshop.env, which scripts/bootstrap.sh generated by reading
# SSM. We source it by an absolute path derived from this script's own location, because
# the Flyte CLI invokes us from whatever directory it happens to be in. Values already
# present in the environment win, so a facilitator can still override by exporting them.

set -eu

# Locate and load the generated config (COGNITO_DOMAIN / COGNITO_CLIENT_ID /
# COGNITO_CLIENT_SECRET / FLYTE_DOMAIN). $0 is the absolute path the CLI called us with.
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ENV_FILE="${SCRIPT_DIR}/../.flyte/workshop.env"
if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
fi

for v in COGNITO_DOMAIN COGNITO_CLIENT_ID COGNITO_CLIENT_SECRET FLYTE_DOMAIN; do
    eval "val=\${$v:-}"
    if [ -z "$val" ]; then
        echo "flyte-token.sh: \$$v is not set, and ${ENV_FILE} didn't supply it." >&2
        echo "Run 'bash scripts/bootstrap.sh' first — it generates that file from SSM." >&2
        exit 1
    fi
done

# The resource server identifier is https://<domain> with an "access" scope; the ALB's
# jwt-validation rule checks for exactly this scope, so it must match the stack.
SCOPE="https://${FLYTE_DOMAIN}/access"

RESPONSE=$(
    curl --silent --show-error --fail-with-body \
         --max-time 20 \
         --request POST "${COGNITO_DOMAIN}/oauth2/token" \
         --user "${COGNITO_CLIENT_ID}:${COGNITO_CLIENT_SECRET}" \
         --data-urlencode "grant_type=client_credentials" \
         --data-urlencode "scope=${SCOPE}" 2>&1
) || {
    echo "flyte-token.sh: token request to Cognito failed." >&2
    echo "  endpoint: ${COGNITO_DOMAIN}/oauth2/token" >&2
    echo "  scope:    ${SCOPE}" >&2
    echo "  response: ${RESPONSE}" >&2
    echo "If this says 'could not resolve host', the Cognito domain is missing from" >&2
    echo "your Kiro network allow-list. See setup/00-kiro-web.md." >&2
    exit 1
}

TOKEN=$(printf '%s' "$RESPONSE" | sed -n 's/.*"access_token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')

if [ -z "$TOKEN" ]; then
    echo "flyte-token.sh: Cognito replied but there was no access_token in the response." >&2
    echo "  response: ${RESPONSE}" >&2
    echo "A common cause is a scope mismatch: FLYTE_DOMAIN must match the domain the" >&2
    echo "devbox stack was deployed with, exactly." >&2
    exit 1
fi

printf '%s' "$TOKEN"
